# Generated by Django 4.2.5 on 2023-10-11 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paciente', models.CharField(max_length=40)),
                ('acuidade', models.CharField(max_length=7)),
                ('idade', models.IntegerField()),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='UserAppointments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optotech.appointment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optotech.user')),
            ],
            options={
                'db_table': 'user_appointments',
            },
        ),
    ]
