# Generated by Django 4.2.5 on 2023-10-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0002_appointment_userappointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userappointments',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='userappointments',
            old_name='user_id',
            new_name='user',
        ),
    ]
