# Generated by Django 4.2.5 on 2023-10-17 14:01

from django.db import migrations, models

def populate_matrix_letters(apps, schema_editor):
    MatrixLetter = apps.get_model('optotech', 'MatrixLetter')
    
    a = [[0,1,1,1,0],[0,1,0,1,0],[0,1,1,1,0],[0,1,0,1,0],[0,1,0,1,0]]
    b = [[1,1,1,1,0],[0,1,0,1,0],[0,1,1,1,0],[0,1,0,1,0],[1,1,1,1,0]]
    c = [[1,1,1,1,0],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],[1,1,1,1,0]]
    d = [[1,1,1,1,1],[0,1,0,0,1],[0,1,0,0,1],[0,1,0,0,1],[1,1,1,1,1]]
    e = [[1,1,1,1,1],[0,1,0,0,1],[0,1,1,0,0],[0,1,0,0,1],[1,1,1,1,1]]
    f = [[1,1,1,1,1],[0,1,0,0,1],[0,1,1,0,0],[0,1,0,0,0],[1,1,1,0,0]]
    g = [[1,1,1,1,1],[1,0,0,0,0],[1,0,1,1,1],[1,0,0,0,1],[1,1,1,1,1]]
    h = [[1,0,0,0,1],[1,0,0,0,1],[1,1,1,1,1],[1,0,0,0,1],[1,0,0,0,1]]
    i = [[0,0,1,0,0],[0,0,0,0,0],[0,0,1,0,0],[0,0,1,0,0],[0,0,1,0,0]]
    j = [[1,1,1,1,1],[0,0,1,0,0],[1,0,1,0,0],[1,0,1,0,0],[1,1,1,0,0]]
    k = [[0,1,0,0,1],[0,1,0,1,0],[0,1,1,0,0],[0,1,0,1,0],[0,1,0,0,1]]
    l = [[1,1,1,0,0],[0,1,0,0,0],[0,1,0,0,0],[0,1,0,0,1],[1,1,1,1,1]]
    m = [[1,1,1,1,1],[1,0,1,0,1],[1,0,1,0,1],[1,0,1,0,1],[1,0,1,0,1]]
    n = [[1,0,0,0,1],[1,1,0,0,1],[1,0,1,0,1],[1,0,0,1,1],[1,0,0,0,1]]
    o = [[1,1,1,1,1],[1,0,0,0,1],[1,0,0,0,1],[1,0,0,0,1],[1,1,1,1,1]]
    p = [[1,1,1,1,1],[0,1,0,0,1],[0,1,1,1,1],[0,1,0,0,0],[1,1,1,0,0]]
    q = [[1,1,1,1,0],[1,0,0,1,0],[1,0,0,1,0],[1,1,1,1,0],[0,0,0,0,1]]
    r = [[1,1,1,1,1],[0,1,0,0,1],[0,1,1,1,1],[0,1,0,1,0],[0,1,0,0,1]]
    s = [[1,1,1,1,1],[1,0,0,0,0],[1,1,1,1,1],[0,0,0,0,1],[1,1,1,1,1]]
    t = [[1,1,1,1,1],[1,0,1,0,1],[0,0,1,0,0],[0,0,1,0,0],[0,1,1,1,0]]
    u = [[1,0,0,0,1],[1,0,0,0,1],[1,0,0,0,1],[1,0,0,0,1],[1,1,1,1,1]]
    v = [[1,0,0,0,1],[1,0,0,0,1],[0,1,0,1,0],[0,1,0,1,0],[0,0,1,0,0]]
    w = [[1,0,1,0,1],[1,0,1,0,1],[1,0,1,0,1],[1,0,1,0,1],[1,1,1,1,1]]
    x = [[1,0,0,0,1],[0,1,0,1,0],[0,0,1,0,0],[0,1,0,1,0],[1,0,0,0,1]]
    y = [[1,0,0,0,1],[0,1,0,1,0],[0,0,1,0,0],[0,0,1,0,0],[0,0,1,0,0]]
    z = [[1,1,1,1,1],[0,0,0,1,0],[0,0,1,0,0],[0,1,0,0,0],[1,1,1,1,1]]

    for row in range(5):
        MatrixLetter.objects.create(
            a="".join([str(val) for val in a[row]]),
            b="".join([str(val) for val in b[row]]),
            c="".join([str(val) for val in c[row]]),
            d="".join([str(val) for val in d[row]]),
            e="".join([str(val) for val in e[row]]),
            f="".join([str(val) for val in f[row]]),
            g="".join([str(val) for val in g[row]]),
            h="".join([str(val) for val in h[row]]),
            i="".join([str(val) for val in i[row]]),
            j="".join([str(val) for val in j[row]]),
            k="".join([str(val) for val in k[row]]),
            l="".join([str(val) for val in l[row]]),
            m="".join([str(val) for val in m[row]]),
            n="".join([str(val) for val in n[row]]),
            o="".join([str(val) for val in o[row]]),
            p="".join([str(val) for val in p[row]]),
            q="".join([str(val) for val in q[row]]),
            r="".join([str(val) for val in r[row]]),
            s="".join([str(val) for val in s[row]]),
            t="".join([str(val) for val in t[row]]),
            u="".join([str(val) for val in u[row]]),
            v="".join([str(val) for val in v[row]]),
            w="".join([str(val) for val in w[row]]),
            x="".join([str(val) for val in x[row]]),
            y="".join([str(val) for val in y[row]]),
            z="".join([str(val) for val in z[row]])
        )


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0004_matrixletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixletter',
            name='a',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='b',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='c',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='d',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='e',
            field=models.CharField(default='00000', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='f',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='g',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='h',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='i',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='j',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='k',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='l',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='m',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='n',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='o',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='p',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='q',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='r',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='s',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='t',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='u',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='v',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='w',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='x',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='y',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='matrixletter',
            name='z',
            field=models.CharField(max_length=40),
        ),
        migrations.RunPython(populate_matrix_letters),

    ]
