# Generated by Django 4.2.5 on 2023-11-01 02:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0007_rename_paciente_aluno_nome_remove_appointment_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserPacientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optotech.paciente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optotech.user')),
            ],
            options={
                'db_table': 'user_pacientes',
            },
        ),
    ]
