# Generated by Django 4.2.5 on 2023-11-02 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0008_aluno_data_criacao_useralunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateTimeField(default=datetime.date(2013, 1, 1)),
            preserve_default=False,
        ),
    ]
