# Generated by Django 4.2.5 on 2023-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0010_appointment_user_delete_userappointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='acuidade',
            field=models.CharField(max_length=6),
        ),
    ]
