# Generated by Django 4.2.5 on 2023-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0014_aluno_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dpi',
            field=models.IntegerField(default=96),
        ),
    ]
