# Generated by Django 4.2.5 on 2023-11-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0015_user_dpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='paciente_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='optotech.userpacientes'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='atendimentos',
        ),
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='userpacientes',
            table='pacientes_usuarios',
        ),
    ]
