# Generated by Django 4.2.5 on 2023-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0016_remove_appointment_paciente_remove_appointment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dpi',
            field=models.IntegerField(null=True),
        ),
    ]
