# Generated by Django 4.2.5 on 2023-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0017_alter_user_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
