# Generated by Django 4.2.5 on 2023-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0018_alter_user_email_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=128),
        ),
    ]
