# Generated by Django 4.2.5 on 2023-12-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0019_alter_paciente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distancia',
            field=models.IntegerField(null=True),
        ),
    ]
