# Generated by Django 4.2.5 on 2023-12-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0020_user_distancia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='distancia',
            new_name='baseFont',
        ),
    ]
