# Generated by Django 4.2.5 on 2023-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0021_rename_distancia_user_basefont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='baseFont',
            field=models.FloatField(null=True),
        ),
    ]
