# Generated by Django 4.2.5 on 2023-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optotech', '0023_alter_user_basefont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='baseFont',
        ),
        migrations.AddField(
            model_name='user',
            name='distancia',
            field=models.FloatField(null=True),
        ),
    ]
