version: "3"
services:
  backend:
    image: backend
    build:
      context: ../
      dockerfile: ./dev-env/backend.dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "../backend/:/src/"
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    container_name: postgres
    volumes: 
      -  "./postgres/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    restart: always
    volumes:
      - "./mongo/:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${POSTGRES_PASSWORD}

