version: "3"
services: 
  frontend:
    image: frontend
    build:
      context: ../
      dockerfile: ./dev-env/frontend.dockerfile
    container_name: frontend
    ports: 
        - "3000:3000"
    restart: always
    volumes:
      - ../frontend/:/src/

  backend:
    image: backend
    build:
      context: ../
      dockerfile: ./dev-env/backend.dockerfile
    container_name: backend    
    ports: 
        - "8000:8000"
    env_file:
        - .env
    depends_on: 
        - postgres
    restart: always
    volumes:
      - ../backend/:/src/

  postgres:     
    image: postgres
    container_name: postgres
    ports: 
        - "5433:5432"
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}    
    restart: always
    volumes:
        - ./postgres:/var/lib/postgres/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./mongo:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: yes      

